[package]
name = "setup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keyring = "2.1.0"
reqwest = { version = "0.11.22", features = ["blocking", "cookies"] }
time = "0.3.30"
whoami = "1.4.1"
